<?xml version="1.0"?>
<robot name="sensor_d405" xmlns:xacro="http://ros.org/wiki/xacro">
  <!-- Includes -->
  <xacro:include filename="$(find realsense2_description)/urdf/_materials.urdf.xacro" />
  <xacro:include filename="$(find realsense2_description)/urdf/_usb_plug.urdf.xacro" />

  <xacro:macro name="sensor_d405" params="parent *origin name:=camera use_nominal_extrinsics:=false add_plug:=false use_mesh:=true">
    <xacro:property name="M_PI" value="3.1415926535897931" />

    <!-- The following values are approximate, and the camera node
     publishing TF values with actual calibrated camera extrinsic values -->
    <xacro:property name="d405_cam_center_to_cam1_offset" value="-0.009"/>
    <xacro:property name="d405_cam_center_to_cam2_offset" value="0.009"/>

    <!-- The following values model the aluminum peripherial case for the
  	D405 camera, with the camera joint represented by the actual
  	peripherial camera tripod mount -->
    <xacro:property name="d405_cam_width" value="0.042"/>
    <xacro:property name="d405_cam_height" value="0.042"/>
    <xacro:property name="d405_cam_depth" value="0.023"/>
    <xacro:property name="d405_cam_mount_from_center_offset" value="0.0149"/>

    <!-- glass cover is 2.7 mm inwards from front aluminium plate -->
    <!-- see datasheet Revision 013, Fig. 4-8 page 83 -->
    <xacro:property name="d405_glass_to_front" value="2.7e-3"/>

    <!-- see datasheet Revision 013, Fig. 4-8 page 85 -->
    <xacro:property name="d405_zero_depth_to_glass" value="3.7e-3"/>
    <!-- convenience precomputation to avoid clutter-->
    <xacro:property name="d405_mesh_x_offset" value="${d405_cam_mount_from_center_offset-d405_glass_to_front-d405_zero_depth_to_glass}"/>

    <!-- The following offset is relative the the physical D405 camera peripherial
  	camera tripod mount -->
    <xacro:property name="d405_cam_center_px" value="${d405_cam_mount_from_center_offset}"/>
    <xacro:property name="d405_cam_center_py" value="0.0"/>
    <xacro:property name="d405_cam_center_pz" value="${d405_cam_height/2}"/>

    <!-- camera body, with origin at bottom screw mount -->
    <joint name="${name}_joint" type="fixed">
      <xacro:insert_block name="origin" />
      <parent link="${parent}"/>
      <child link="${name}_bottom_screw_frame" />
    </joint>
    <link name="${name}_bottom_screw_frame"/>

    <joint name="${name}_link_joint" type="fixed">
      <origin xyz="${d405_mesh_x_offset} ${d405_cam_center_py} ${d405_cam_center_pz}" rpy="0 0 0"/>
      <parent link="${name}_bottom_screw_frame"/>
      <child link="${name}_link" />
    </joint>

    <link name="${name}_link">
      <visual>
        <xacro:if value="${use_mesh}">
          <!-- the mesh origin is at front plate in between the two camera axes -->
          <origin xyz="${d405_zero_depth_to_glass + d405_glass_to_front} ${-d405_cam_center_py} 0" rpy="${M_PI/2} 0 ${M_PI/2}"/>
          <geometry>
            <mesh filename="package://realsense2_description/meshes/d405.dae" />
          </geometry>
        </xacro:if>
        <xacro:unless value="${use_mesh}">
          <origin xyz="0 ${d405_cam_center_py} 0" rpy="0 0 0"/>
          <geometry>
            <box size="${d405_cam_depth} ${d405_cam_width} ${d405_cam_height}"/>
          </geometry>
          <material name="aluminum"/>
        </xacro:unless>     
      </visual>
      <collision>
        <origin xyz="0 ${d405_cam_center_py} 0" rpy="0 0 0"/>
        <geometry>
          <box size="${d405_cam_depth} ${d405_cam_width} ${d405_cam_height}"/>
        </geometry>
      </collision>
      <inertial>
        <!-- The following are not reliable values, and should not be used for modeling -->
        <mass value="0.060" />
        <origin xyz="0 0 0" />
        <inertia ixx="0.003881243" ixy="0.0" ixz="0.0" iyy="0.000498940" iyz="0.0" izz="0.003879257" />
      </inertial>
    </link>

    <!-- Use the nominal extrinsics between camera frames if the calibrated extrinsics aren't being published. e.g. running the device in simulation  -->
    <xacro:if value="${use_nominal_extrinsics}">
      <joint name="${name}_cam1_joint" type="fixed">
        <origin xyz="0 ${d405_cam_center_to_cam1_offset} 0" rpy="0 0 0" />
        <parent link="${name}_link" />
        <child link="${name}_cam1_frame" />
      </joint>
      <link name="${name}_cam1_frame"/>

      <joint name="${name}_cam1_optical_joint" type="fixed">
        <origin xyz="0 0 0" rpy="${-M_PI/2} 0 ${-M_PI/2}" />
        <parent link="${name}_cam1_frame" />
        <child link="${name}_cam1_optical_frame" />
      </joint>
      <link name="${name}_cam1_optical_frame"/>

      <joint name="${name}_cam2_joint" type="fixed">
        <origin xyz="0 ${d405_cam_center_to_cam2_offset} 0" rpy="0 0 0" />
        <parent link="${name}_link" />
        <child link="${name}_cam2_frame" />
      </joint>
      <link name="${name}_cam2_frame"/>

      <joint name="${name}_cam2_optical_joint" type="fixed">
        <origin xyz="0 0 0" rpy="${-M_PI/2} 0 ${-M_PI/2}" />
        <parent link="${name}_cam2_frame" />
        <child link="${name}_cam2_optical_frame" />
      </joint>
      <link name="${name}_cam2_optical_frame"/>
    </xacro:if>

    <xacro:if value="${add_plug}">
      <xacro:usb_plug parent="${name}_link" name="${name}_usb_plug">
        <!-- see datasheet Revision 013, Fig. 4-8 page 88 -->
        <origin xyz="${-d405_mesh_x_offset-0.00835+0.00682} ${d405_cam_width/2} 0" rpy="${M_PI} 0 0"/>
      </xacro:usb_plug>
    </xacro:if>
  </xacro:macro>
</robot>
